name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [csharp, python]

    steps:
      - uses: actions/checkout@v3

      # Python setup and test
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run Python tests
        if: matrix.language == 'python'
        run: |
          cd python
          PYTHONPATH=. pytest

      # C# setup and test
      - name: Set up .NET
        if: matrix.language == 'csharp'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run .NET tests
        if: matrix.language == 'csharp'
        run: |
          cd csharp
          dotnet test